[features]
seeds = false
skip-lint = false
[programs.localnet]
dagoats_sweepstake = "AuDm9hEenfd8WgNHjr49dcApSBXWhzYkwrwPsHMvVAdE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/pracovni/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
